module:
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_bootstrap_grid: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_layout: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  fontawesome: 0
  help: 0
  history: 0
  image: 0
  imagemagick: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  paragraph_blocks: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  sendgrid_integration: 0
  shortcut: 0
  simple_recaptcha: 0
  simple_recaptcha_webform: 0
  social_icons: 0
  sophron: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  fontyourface: 1
  menu_link_content: 1
  webform_bootstrap: 1
  google_fonts_api: 10
  local_fonts: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  dcmanila2020: 0
  bootstrap: 0
  dcm_manila_2020: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
