schemas:
  bootstrap: 8000
  dcm_manila_2020: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://voj-bs-dcmanila-2020.pantheonsite.io/themes/custom/dcm_manila_2020/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://header-logo.png'
  url: ''
  use_default: 0
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer2: ''
  footer: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
navbar_position: static-top
